### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by karmatosed** [WPTRT/doingitwrong#1]
Is there any documentation that I'm missing where everything is listed? We need a list of everything that is wrong. https://github.com/WPTRT/doingitwrong/wiki looks oh so empty :(

**Comment by grappler** [comment]
I am thinking the documentation should be a file in the theme so that it is included when downloaded as the wiki might not be accessible when there is no internet.

**Comment by karmatosed** [comment]
The problem with it being a file is that people will be testing all files in the theme. I think using the wiki therefore makes more sense. It's a little like giving the test results with the test otherwise.

The contribution pack can mirror the wiki - that will be offline readable as downloaded.

**Comment by ghost** [comment]
It wouldn't hurt being both, should there be no internet connection you can refer the file you've downloaded which will also be stated within the wiki, online (as you'll read it the first time when downloading the theme).
